#!/usr/bin/env bash

set -e

#--------------------------------------------------------------
# variables
#--------------------------------------------------------------

OUTPUT_DIR="output"
INPUT_DIR="input"
BIN_DIR="$(realpath .)"
VIP_DIR="$(realpath ../../)"
TOP_DIR="$(realpath ../tb_sv)"
DPI_DIR="$(realpath ../../c_model)"


#--------------------------------------------------------------
# function declaration
#--------------------------------------------------------------
error() {
  >&2 echo "ERROR: $@"
  exit 1
}

bin_exists() {
  if type $1 &> /dev/null; then
    return 0
  fi
  return 1
}

run_xrun() {
  gcc $DPI_DIR/aes_model.c $DPI_DIR/aes_model.h -std=c99

  xrun -q \
    -access +rw -vtimescale 1ns/1ps \
    -uvmhome $(ncroot)/tools/methodology/UVM/CDNS-1.2 \
    -v200x \
    +incdir+$VIP_DIR \
    +incdir+$DPI_DIR \
    +incdir+$TOP_DIR \
    +incdir+$TOP_DIR/test \
    -F $BIN_DIR/dut_files.f \
    $VIP_DIR/aes_pkg.sv \
    $VIP_DIR/aes_if.sv \
    $TOP_DIR/aes_test_pkg.sv \
    $TOP_DIR/aes_th.sv \
    $TOP_DIR/aes_tb.sv \
    +UVM_VERBOSITY=UVM_MEDIUM $*
}
#+UVM_TESTNAME=aes_test_decipher 

#--------------------------------------------------------------
# execution
#--------------------------------------------------------------
[ -d "$VIP_DIR" ] || error "$VIP_DIR does not exist"
[ -d "$TOP_DIR" ] || error "$TOP_DIR does not exist"
[ -d "$DPI_DIR" ] || error "$TOP_DIR does not exist"


mkdir -p output
cd output

if bin_exists xrun; then
  run_xrun $*
else
  error "simulator not found"
fi


